version: 2.1

jobs:
  checkout_and_unit_test:
    machine: true
    steps:
      - run: echo "Checkout and unit test."

  deploy_backend:
    machine: true
    steps:
      - run: echo "Deploy backend."

  integration_test_backend:
    machine: true
    steps:
      - run: echo "Integration test backend."

  deploy_staging:
    machine: true
    steps:
      - run: echo "Deploy staging."

  acceptance_tests_1:
    machine: true
    steps:
      - run: echo "Acceptance test 1."

  acceptance_tests_2:
    machine: true
    steps:
      - run: echo "Acceptance test 2."

  acceptance_tests_3:
    machine: true
    steps:
      - run: echo "Acceptance test 3."

  acceptance_tests_4:
    machine: true
    steps:
      - run: echo "Acceptance test 4."

  deploy_production:
    machine: true
    steps:
      - run: echo "Deploy production."

workflows:
  monWorkflow:
    jobs:
      - checkout_and_unit_test

      - deploy_backend:
          requires:
            - checkout_and_unit_test

      - integration_test_backend:
          requires:
            - deploy_backend

      - deploy_staging:
          requires:
            - integration_test_backend

      - acceptance_tests_1:
          requires:
            - deploy_staging

      - acceptance_tests_2:
          requires:
            - deploy_staging

      - acceptance_tests_3:
          requires:
            - deploy_staging

      - acceptance_tests_4:
          requires:
            - deploy_staging

      - deploy_production:
          requires:
            - acceptance_tests_1
            - acceptance_tests_2
            - acceptance_tests_3
            - acceptance_tests_4
