version: 2.1

jobs:
  sayhello:
    description: A job that says Hello
    machine: true
    steps:
      - run: echo "Hello World!"
      - run: echo "Hello Logan!"

workflows:
  monWorkflow:
    jobs:
      - sayhello
